concesionario/concesionario/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import include, url
from django.contrib import admin
from concesionario import settings

urlpatterns = [

	url(r'^admin/', include(admin.site.urls)),
    url(r'', include('apps.inicio.url',namespace='inicio')),
    url(r'', include('apps.cuenta.url',namespace='cuenta')),
    url(r'', include('apps.cotizacion.url',namespace='cotizacion')),
    url(r'', include('apps.cliente.url',namespace='cliente')),
    url(r'', include('apps.empleado.url',namespace='empleado')),
    url(r'', include('apps.repuesto.url',namespace='repuesto')),
    url(r'', include('apps.sucursal.url',namespace='sucursal')),
    url(r'', include('apps.vehiculo.url',namespace='vehiculo')),
    url(r'', include('apps.venta.url',namespace='venta')),
    url(r'', include('apps.proveedor.url',namespace='proveedor')),
     url(r'', include('apps.reporte.url',namespace='reporte')),
    url(r'', include('apps.orden_de_trabajo.url',namespace='orden_de_trabajo')),
    url(r'', include('apps.cotizacion_orden_de_trabajo.url',namespace='cotizacion_orden_de_trabajo')),
	url(r'', include('apps.factura_orden_de_trabajo.url',namespace='factura_orden_de_trabajo')),
    url(r'', include('apps.movil.url',namespace='movil')),

    #url para acceder a la imagenes que estan en la carpeta media del proyecto
    #se deseas colocar imagenes en tu contenido HTML, este link es necesario para que se muestren las imagenes
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),

]

concesionario/apps/cotizacion/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from datetime import datetime
from apps.empleado.models import Empleado
from apps.cliente.models import Cliente
from apps.vehiculo.models import Vehiculo


# Forma de pago en que se realiza la compra
CREDITO = 'Credito'
EFECTIVO = 'Efectivo'
TARJETA_CREDITO = 'Tarjeta_credito'
TARJETA_DEBITO = 'Tarjeta_debito'

forma_pago_choices = (
	(CREDITO, 'Credito'),
	(EFECTIVO, 'Efectivo'),
	(TARJETA_CREDITO, 'Tarjeta de credito'),
	(TARJETA_DEBITO, 'Tarjeta de debito'),
)

#
class Cotizacion(models.Model):
	"""Define la organizacion del los datos de una cotizacion en la base de datos."""

	#Empleado que realiza la cotizacion, relacion uno a muchos
	empleado= models.ForeignKey(Empleado)
	#Cliente que solicita la cotizacion, relacion uno a muchos
	cliente= models.ForeignKey(Cliente)
	#Vehiculo cotizado, relacion uno a muchos
	vehiculo= models.ForeignKey(Vehiculo)
	#Fecha en que se realiza la cotizacion
	fecha=models.DateField(auto_now_add=True)
	#Fecha de vencimiento de la cotizacion
	fecha_vencimiento=models.DateField()
	#Forma de pago en la que se realiza la cotizacion
	forma_pago = models.CharField(max_length=20,choices=forma_pago_choices, default=EFECTIVO)
	#Estado de la cotizacion, Activa/inactiva
	habilitado = models.BooleanField(default = True)

	#Permite hacer modificaciones agregadas a la representacion del modelo
	class Meta:
		ordering = ['fecha']
		verbose_name_plural = "Cotizaciones"

	#Permite determinar una representacion en string del objeto
	def __str__(self):
		return self.fecha

	#Permite determinar una represetacion en string para el objeto (Esto es para versiones de Python 2)
	def __unicode__(self):
		return self.fecha

concesionario/apps/cotizacion/forms.py
# -*- encoding: utf-8 -*-
from django.core.urlresolvers import reverse_lazy, reverse
from django import forms
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.generic.edit import CreateView, UpdateView
from .models import Cotizacion
from apps.cliente.models import Cliente
from apps.empleado.models import Empleado
from apps.vehiculo.models import Vehiculo
from django.contrib import messages
from apps.inicio.mixins import LoginRequiredMixin

class CrearCotizacion(LoginRequiredMixin,CreateView):
	fecha_vencimiento=forms.DateField(
		widget=forms.widgets.DateInput(format="%y-%m-%d"))
	model = Cotizacion
	fields = [ 'cliente', 'vehiculo', 'fecha_vencimiento', 'forma_pago']

	def get_context_data(self,**kwargs):

		context = super(CrearCotizacion,self).get_context_data(**kwargs)
		context['search_button_text'] = 'Completar Formulario'

		clientes = Cliente.objects.all()
		context['lista_clientes'] = clientes

		vehiculos = Vehiculo.objects.all()
		context['vehiculos'] = vehiculos

		return context

	def post(self, request, *args, **kwargs):

		empleado = Empleado.objects.get(user_id=self.request.user.id)
		cliente = Cliente.objects.get(pk=request.POST["cliente"])
		vehiculo = Vehiculo.objects.get(pk=request.POST["vehiculo"])
		forma_pago = request.POST["forma_pago"]
		fecha_vencimiento=  request.POST["fecha_vencimiento"]
		print fecha_vencimiento
		cotizacion = Cotizacion(empleado = empleado, cliente = cliente, vehiculo = vehiculo, fecha_vencimiento=fecha_vencimiento,forma_pago = forma_pago)
		cotizacion.save()
		context = {'cotizacion':cotizacion}
		return render_to_response(
			'cotizacion/cotizacionPDF.html',
			context,
			context_instance=RequestContext(request)
		)

class ActualizarCotizacion(LoginRequiredMixin, UpdateView):
	model = Cotizacion
	fields = ['empleado', 'cliente', 'vehiculo', 'fecha','fecha_vencimiento', 'forma_pago']
	def get_success_url(self):
		messages.info(self.request,"Cotización creada con exito")
		return  reverse_lazy('cotizacion:listar')

concesionario/apps/cotizacion/views.py
# -*- encoding: utf-8 -*-

from django.views.generic import ListView
from .models import Cotizacion
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.generic import TemplateView
from apps.inicio.mixins import LoginRequiredMixin

class ListaCotizaciones(LoginRequiredMixin,ListView):
	model = Cotizacion
	context_object_name = 'lista_cotizaciones'



class PdfCreateView(LoginRequiredMixin,TemplateView):
	def get(self,request,*args,**kwargs):
		cotizacion= Cotizacion.objects.get(id=kwargs['pk'])
		context = {'cotizacion':cotizacion}

		return render_to_response(
			'cotizacion/cotizacionPDF.html',
			context,
			context_instance=RequestContext(request)
		)

concesionario/apps/cotizacion/templates/cotizacion/cotizacionPDF.html
{% extends "base.html" %}
{% load staticfiles %}
{% load factura_tags %}
{% block css %}
{{ block.super }}
  <link href="{% static 'color_admin/assets/css/invoice-print.min.css' %}" rel="stylesheet" />
{% endblock %}
{% block section_title %}{% endblock %}
{% block section_subtitle %}{% endblock %}
{% block content %}
            <!-- begin invoice -->
            <div class="invoice">

                <div class="row invoice-company">
                    <div class="row pull-left">
                      <img src="{{ MEDIA_URL }}imagenes/logo/logo.png" class="img-circle">
                    </div>
                    <span class="pull-right hidden-print">
                      <a href="javascript:;" onclick="window.history.back()" class="btn btn-sm btn-success m-b-10"><i class="fa fa-arrow-circle-left"></i> Volver</a>
                      <a href="javascript:;" onclick="window.print()" class="btn btn-sm btn-success m-b-10"><i class="fa fa-print m-r-5"></i> Imprimir</a>
                    </span>
                </div>
                <div class="row invoice-header">
                    <div class="invoice-from">
                        <address class="m-t-5 m-b-5">
                            <strong>{{ user.empleado.sucursal.nombre }}, Inc.</strong><br />
                            {{ user.empleado.sucursal.direccion }}<br />
                            {{ user.empleado.sucursal.ciudad }}<br />
                            Telefono: (032) {{ user.empleado.sucursal.telefono }}<br />
                        </address>
                    </div>
                    <div class="invoice-to">
                        <address class="m-t-5 m-b-5">
                           <strong>Señor(a):
                            </strong><br />
                            {{ cotizacion.cliente.nombre }} {{ cotizacion.cliente.apellido }}<br />
                            Telefono: (032) {{ cotizacion.cliente.telefono }}<br />
                            Celular: {{ cotizacion.cliente.celular }}
                        </address>                     
                    
                    </div>
                    <div class="invoice-to">
                          <strong>  Cotización: {{ cotizacion.id }}</strong><br />
                            Fecha De Emisión:<br />{% now 'SHORT_DATE_FORMAT' %}<br />
                             Vigente hasta:  <br />
                             {{ cotizacion.fecha_vencimiento}}
                        
                    </div></div>

                     <div class="invoice" align="center" >
                         <img src={{ cotizacion.vehiculo.imagen.url }} alt="" WIDTH=400 HEIGHT=200 /> 
                          </div>
  
                            <div class="row">
                               <div class="table-responsive" align="center"> 
                                    
                                         <table class="table table-striped table-bordered">
                                        <thead>
                                        <tr>
                                    <th>VEHICULO</th>
                                    <th>MODELO</th>
                                    <th>PRECIO</th>
                                    <th>POTENCIA</th>
                                    <th>MOTOR</th>

                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td><small> {{ cotizacion.vehiculo.marca }}</small></td>
                                    <td> {{cotizacion.vehiculo.modelo}}</td>
                                    <td>${{ cotizacion.vehiculo.precio}}</td>
                                    <td>{{ cotizacion.vehiculo.potencia}}</td>
                                    <td>{{ cotizacion.vehiculo.motor}}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    </div>
                    <div><strong>Notas:</strong> Precios, condiciones de pago y especificaciones técnicas sujetas a cambios sin previo aviso. Disponibilidad sujeta a SIGIA.</div>
                    

                <div class="invoice-footer text-muted">
                    <p class="text-center m-b-5">
                       Sistema de Gestion de Inventario Automotriz
                    </p>
                    <p class="text-center">
                        <span class="m-r-10"><i class="fa fa-globe"></i> www.SIGIA.com</span>
                        <span class="m-r-10"><i class="fa fa-phone"></i> T:(032){{ user.empleado.sucursal.telefono }}</span>
                        <span class="m-r-10"><i class="fa fa-envelope"></i> {{ user.email }}</span>
                    </p>
                </div>
            </div>
             </div>
            <!-- end invoice -->
{% endblock %}
{% block javascript %}
{{ block.super }}
{% endblock %}

concesionario/apps/cotizacion/templates/cotizacion/cotizacion_form.html
 {% extends "base.html" %}
{% load staticfiles %}

{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block css %}
{{ block.super }}

       <!-- ================== BEGIN PAGE LEVEL STYLE ================== -->
    <link href="{% static 'color_admin/assets/plugins/bootstrap-wizard/css/bwizard.min.css' %}" rel="stylesheet" />
        <!-- Para gestionar Fechas -->
    <link href="{% static 'color_admin/assets/plugins/bootstrap-datepicker/css/datepicker.css'%}" rel="stylesheet" />
    <link href="{% static 'color_admin/assets/plugins/bootstrap-datepicker/css/datepicker3.css'%}" rel="stylesheet" />
    <!-- fin Para gestionar Fechas -->
    <!-- ================== END PAGE LEVEL STYLE ================== -->
{% endblock %}

{% block breadcrumb %}
Gestión de Cotizaciones
{% endblock %}
{% block section_title %} Nueva Cotización{{ section_title }}{% endblock %}
{% block section_subtitle %}Diligencie el siguiente formulario{% endblock %}
{% block content %}

    <!-- begin col-12 --><div class="row">
    <!-- begin col-12 -->
    <div class="col-md-12">
        <!-- begin panel -->
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
              </div>Nueva Cotización</h4>
            </div>
            <div class="panel-body">
                <form action="{{ request.path }}" method="POST" data-parsley-validate="true" name="form-wizard" enctype="multipart/form-data" >{% csrf_token %}
                    <div id="wizard">
                        <ol>
                           <li>
                                Cliente
                                <small>Seleccione el Cliente.</small>
                                <small></small>
                            </li>
                            <li>
                                Vehículo
                                <small> Seleccione el Vehículo</small>
                            </li>
                            <li>
                                Información General
                                <small></small>
                            </li>
                        </ol>
                        <!-- begin wizard step-1 -->
                        <div class="wizard-step-1">
                            <fieldset>
                                <div class="row">
                                    <div class="table-responsive">
                                    <table class="table table-striped table-bordered">
                                        <thead>
                                            <tr>
                                            <th>Identificación</th>
                                            <th>Nombre</th>
                                            <th>Apellido</th>
                                            <th>Ciudad</th>
                                            <th>Departamento</th>
                                            <th>Teléfono</th>
                                            <th>Celular</th>
                                            <th>Email</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% if lista_clientes %}
                                            {% for cliente  in lista_clientes %}
                                            <tr>
                                                <td><a class="clienteID" name="{{cliente.pk}}"> {{ cliente.identificacion }}</a></td>
                                                <td>{{ cliente.nombre }}</td>
                                                <td>{{ cliente.apellido }}</td>
                                                <td>{{ cliente.ciudad }}</td>
                                                <td>{{ cliente.departamento }}</td>
                                                <td>{{ cliente.telefono }}</td>
                                                <td>{{ cliente.celular }}</td>
                                                <td>{{ cliente.email }}</td>
                                            {% endfor %}
                                        {% else %}
                                        <p><h2>No hay Clientes registrados.</h2></p>
                                            {% endif %}
                                        </tbody>
                                    </table>
                                </div>

                                </div>
                            </fieldset>
                        </div>

                          <div class="wizard-step-2">
                            <fieldset>
                                <div class="row">

                                <div class="panel-body">
                                    <div class="table-responsive">
                                        <table class="table table-striped table-bordered">
                                            <thead>
                                                <tr>
                                                    <th>Nº de serie</th>
                                                    <th>Marca</th>
                                                    <th>Modelo</th>
                                                    <th>Imagen</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            {% for vehiculo  in vehiculos %}
                                                <tr>
                                                    <td><a class="vehiculoID" href="{% url 'vehiculo:actualizar' vehiculo.pk %}"> {{ vehiculo.numero_serie }}</a></td>
                                                    <td>{{ vehiculo.marca }}</td>
                                                    <td>{{ vehiculo.modelo }}</td>
                                                    <td>{% if  vehiculo.imagen %}
                                                            <img src={{ vehiculo.imagen.url }} width=50 height=50 class="media-object rounded-corner"/>
                                                        {% else %}
                                                            <img src="{{ MEDIA_URL }}imagenes/vehiculos/imagen_no_disponible.jpg" width=50 height=50 class="media-object rounded-corner" />
                                                        {% endif %} </td>
                                                </tr >
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>

                                </div>
                            </fieldset>
                        </div>
                        <!-- end wizard step-2 -->
                        <!-- begin wizard step-3 -->
                        <div class="wizard-step-3">
                            <fieldset>
                                <div class="row">
                                  <div class="col-md-8 col-md-offset-2">
                                      {% bootstrap_form form %}
                                      <div class="pull-right" >
                                          <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-cog"></i> Guardar</button>
                                      </div>
                                  </div>
                                  </div>
                            </fieldset>
                        </div>
                        <!-- end wizard step-3 -->
                    </div>

                </form>
            </div>
        </div>
        <!-- end panel -->
    </div>
    <!-- end col-8-->

</div>
{% endblock %}

{% block javascript %}
{{ block.super }}
<!-- ================== BEGIN PAGE LEVEL JS ================== -->
<!-- Para funcionamiento de tablas -->
<script src="{% static 'color_admin/assets/plugins/DataTables-1.9.4/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'color_admin/assets/plugins/DataTables-1.9.4/js/data-table.js' %}"></script>

<script src="{% static 'color_admin/assets/plugins/parsley/dist/parsley.js' %}"></script>
<script src="{% static 'color_admin/assets/plugins/bootstrap-wizard/js/bwizard.js' %}"></script>
<script src="{% static 'color_admin/assets/js/form-wizards-validation.demo.min.js' %}"></script>
<script src="{% static 'color_admin/assets/js/apps.min.js' %}"></script>
<script src="{% static 'color_admin/assets/js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'color_admin/assets/plugins/DataTables-1.9.4/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'color_admin/assets/plugins/DataTables-1.9.4/js/data-table.js' %}"></script>
<!-- ================== END PAGE LEVEL JS ================== -->
<script>
    $(document).ready(function() {
        FormWizardValidation.init();
         $("#id_empleado").attr('readonly','readonly');
         $("#id_cliente").attr('readonly','readonly');
         $("#id_vehiculo").attr('readonly','readonly');

        $(".clienteID").click( function (event){
            event.preventDefault();
            var clickedClienteId = $(this).attr('name');
            $("#id_cliente").val(clickedClienteId);
            $(".next").click();
        });
        $(".vehiculoID").click( function (event){
            event.preventDefault();
            var clickedVehiculoId = $(this).attr('href').split("/")[2];
            $("#id_vehiculo").val(clickedVehiculoId);
            $(".next").click();
        });
        $('#id_fecha_vencimiento').datepicker({todayHighlight:true,autoclose:true});

    });
</script>

{% endblock %}

concesionario/apps/cotizacion/templates/cotizacion/cotizacion_list.html
{% extends "base.html" %}
{% load staticfiles %}
 
{% block css %}
{{ block.super }}
    <link href="{% static 'color_admin/assets/plugins/DataTables-1.9.4/css/data-table.css' %}" rel="stylesheet" />
{% endblock %}
{% block breadcrumb %}
Gestion de Cotizaciones
{% endblock %}
{% block section_title %}Cotizaciónes{% endblock %}
{% block section_subtitle %}Seleccione la cotización que desea ver{% endblock %}
{% block content %}
                <!-- begin col-12 -->
                <div class="col-md-12">
                    <!-- begin panel -->
                    <div class="panel panel-inverse">
                        <div class="panel-heading">
                            <div class="panel-heading-btn">
                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                            </div>
                            <h4 class="panel-title">Cotizaciones</h4>
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table id="data-table" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                        <th>Número de Cotización</th>
                                        <th>Cliente</th>
                                        <th>Vehiculo</th>
                                        <th>Fecha</th>
                                        <th>Fecha Vencimiento</th>
                                        <th>Forma Pago</th>
                                        <th>Vendedor</th>
                                         </tr>
                                    </thead>
                                     <tbody>
                            {% if lista_cotizaciones %} 
                            {% for cotizacion  in lista_cotizaciones %}
                                <tr>
                                     <td><a href="{% url 'cotizacion:pdf' cotizacion.pk %}">{{ cotizacion.pk }}</td>
                                    <td>{{ cotizacion.cliente}}</td>
                                    <td>{{ cotizacion.vehiculo }}</td>
                                    <td>{{ cotizacion.fecha }}</td>
                                    <td>{{ cotizacion.fecha_vencimiento }}</td>
                                    <td>{{ cotizacion.forma_pago }}</td>
                                    <td>{{ cotizacion.empleado }}</td>
                                                                         
                            {% endfor %} 
                        {% else %} 
                            <p><h2>No hay Cotizaciones Realizadas.</h2></p>
                    {% endif %}                       
                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!-- end panel -->
                </div>
                <!-- end col-12 --> 
{% endblock %}

{% block javascript %}
{{ block.super }}

    <!-- ================== BEGIN PAGE LEVEL JS TABLE ================== -->
    <script src="{% static 'color_admin/assets/plugins/DataTables-1.9.4/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'color_admin/assets/plugins/DataTables-1.9.4/js/data-table.js' %}"></script>
    <script src="{% static 'color_admin/assets/js/apps.min.js' %}"></script>
    <script src="{% static 'color_admin/assets/js/inbox.demo.min.js' %}"></script>
    <script src="{% static 'color_admin/assets/js/apps.min.js' %}"></script>
    <!-- ================== END PAGE LEVEL JS ================== -->

{% endblock %}

concesionario/apps/cotizacion/templates/cotizacion/crear.html
{% extends "base.html" %}
{% load staticfiles %}

{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<!-- css auxiliar -->
{% block custom-css %}
	<!-- ================== BEGIN PAGE LEVEL STYLE ================== -->
	<link href="{% static 'color_admin/assets/plugins/bootstrap-wizard/css/bwizard.min.css' %}" rel="stylesheet" />
	<!-- Para gestionar Fechas -->
	<link href="{% static 'color_admin/assets/plugins/bootstrap-datepicker/css/datepicker.css'%}" rel="stylesheet" />
 	<link href="{% static 'color_admin/assets/plugins/bootstrap-datepicker/css/datepicker3.css'%}" rel="stylesheet" />
 	<!-- fin Para gestionar Fechas -->

	<!-- ================== END PAGE LEVEL STYLE ================== -->
{% endblock %}

<!-- Enacabezado de la seccion -->
{% block content %}
	<!-- begin #page-container -->
	<div id="page-container" class="fade page-sidebar-fixed page-header-fixed">
		
		<!-- begin #header -->
		{% include "includes/header.html" %}
		<!-- end #header -->
		
		<!-- begin #sidebar -->
		{% include "includes/sidebar.html" %}
		<!-- end #sidebar -->
		
		<!-- begin #content -->
		<div id="content" class="content">
			<!-- begin page-header -->
			<h1 class="page-header">Cotizaciones</h1>
			<!-- end page-header -->
			
			<!-- begin indicators -->
			{% include "includes/indicadores.html"%}
			<!-- end indicators -->
						
			<!-- begin row -->
			<div class="row">

				<!-- begin col-8 -->
				<div class="col-md-8">
					<!-- begin col-12 -->
				    <div class="col-md-12">
				        <!-- begin panel -->
	                    <div class="panel panel-inverse">
	                        <div class="panel-heading">
	                            <div class="panel-heading-btn">
	                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
	                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
	                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
	                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
	                            </div>
	                            <h4 class="panel-title">Nueva cotización</h4>
	                        </div>
	                        <div class="panel-body">
	                        	{# Display a form #}
	                        	{# the enctype="multipart/form-data" is necessary to upload files#}
	                            <form action="{% url 'cotizacion:crear' %}" method="POST" enctype="multipart/form-data"> {% csrf_token %}
	                            {% bootstrap_form form %}
									<div id="wizard">
										
										<button type="submit" class="btn btn-inverse"><i class="fa fa-cog"></i> Generar</button>
										
										
									</div>
								</form>
	                        </div>
	                    </div>
	                    <!-- end panel -->
	                </div>
	                <!-- end col-12 -->
	            </div>
	            <!-- end col-8 -->

				<!-- begin col-4 -->
				<div class="col-md-4">
				{% include "includes/calendario.html" %}
				</div>
				<!-- end col-4 -->
			</div>
			<!-- end row -->
		</div>
		<!-- end #content -->
	
		
		<!-- begin scroll to top btn -->
		<a href="javascript:;" class="btn btn-icon btn-circle btn-success btn-scroll-to-top fade" data-click="scroll-top"><i class="fa fa-angle-up"></i></a>
		<!-- end scroll to top btn -->
	</div>
	<!-- end page container -->
{% endblock %}

<!-- JavaScript auxiliar -->
{% block custom-js %}
	<!-- ================== BEGIN PAGE LEVEL JS ================== -->
	<script src="{% static 'color_admin/assets/plugins/bootstrap-wizard/js/bwizard.js' %}"></script>
	<script src="{% static 'color_admin/assets/js/form-wizards.demo.min.js' %}"></script>
	<script src="{% static 'color_admin/assets/js/apps.min.js' %}"></script>
	
	<!-- Para gestionar Fechas -->
	<script src="{% static 'color_admin/assets/js/bootstrap-datepicker.js' %}"></script>

	<script>
		$(document).ready(function(){
			$('#id_fecha').datepicker({todayHighlight:true,autoclose:true});
			$('#id_fecha_vencimiento').datepicker({todayHighlight:true,autoclose:true});

		});
	</script>
	<!-- fin Para gestionar Fechas -->

	<!-- ================== END PAGE LEVEL JS ================== -->
{% endblock %}